# Generated by Django 2.2.12 on 2021-07-09 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_passengers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Passengers',
            new_name='Passenger',
        ),
    ]
